### ISSUE TITLE
Doesn't work on X1 Carbon Gen 7 nor ThinkPad TrackPoint Keyboard II

### ISSUE THREAD

**Issue by mateuszwieloch** [VP1147/thinker#3] opened 2020-11-11 23:23 UTC
I've installed tp-smapi-dkms with `apt install tp-smapi-dkms` but still getting:
```
$ ./thinker.sh
Couldn't find trackpoint device.
```
Other info:
```
$ ls /sys/devices/platform/i8042/serio1
bind_mode    driver@  firmware_id  input/    power/	     protocol	resetafter  resync_time  subsystem@
description  drvctl   id/	  modalias  press_to_select  rate	resolution  sensitivity  uevent
```
Output of `tree /proc` [in my cloud drive due to output size](http://u.pc.cd/HFbotalK)

**Comment by VP1147** [comment] 2020-11-18 11:22
Please send the output of
`xinput list`

**Comment by mateuszwieloch** [comment] 2020-11-19 21:47
Output **without** external monitor and TrackPoint Keyboard II:
```
$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SYNA8004:00 06CB:CD8B Mouse             	id=10	[slave  pointer  (2)]
⎜   ↳ SYNA8004:00 06CB:CD8B Touchpad          	id=11	[slave  pointer  (2)]
⎜   ↳ TPPS/2 Elan TrackPoint                  	id=14	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ sof-hda-dsp Headset Jack                	id=12	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=13	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=15	[slave  keyboard (3)]
```
And now **with** external monitor and keyboard:
```
$ xinput list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SYNA8004:00 06CB:CD8B Mouse             	id=10	[slave  pointer  (2)]
⎜   ↳ SYNA8004:00 06CB:CD8B Touchpad          	id=11	[slave  pointer  (2)]
⎜   ↳ TPPS/2 Elan TrackPoint                  	id=14	[slave  pointer  (2)]
⎜   ↳ Lenovo TrackPoint Keyboard II Mouse     	id=16	[slave  pointer  (2)]
⎜   ↳ Lenovo TrackPoint Keyboard II Consumer Control	id=19	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=9	[slave  keyboard (3)]
    ↳ sof-hda-dsp Headset Jack                	id=12	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=13	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=15	[slave  keyboard (3)]
    ↳ Lenovo TrackPoint Keyboard II           	id=17	[slave  keyboard (3)]
    ↳ Lenovo TrackPoint Keyboard II System Control	id=18	[slave  keyboard (3)]
    ↳ Lenovo TrackPoint Keyboard II Consumer Control	id=20	[slave  keyboard (3)]
    ↳ HD Pro Webcam C920                      	id=21	[slave  keyboard (3)]
```

**Comment by VP1147** [comment] 2020-11-20 13:39
Now `xinput list "Lenovo TrackPoint Keyboard II Mouse"`
The problems are apparently caused by the absence of sysfs files on newer Thinkpad models or Trackpoint keyboards.
My T410 returned this:
`
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=10	[slave  pointer  (2)]
⎜   ↳ **TPPS/2 IBM TrackPoint                   	id=11	[slave  pointer  (2)]**
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=9	[slave  keyboard (3)]
    ↳ ThinkPad Extra Buttons                  	id=12	[slave  keyboard (3)]
`
'll need to find a more compatible way to communicate with the device, maybe by Xinput.

**Comment by mateuszwieloch** [comment] 2020-11-22 01:29
```
$ xinput list "Lenovo TrackPoint Keyboard II Mouse"
Lenovo TrackPoint Keyboard II Mouse     	id=10	[slave  pointer  (2)]
	Reporting 7 classes:
		Class originated from: 10. Type: XIButtonClass
		Buttons supported: 7
		Button labels: "Button Left" "Button Middle" "Button Right" "Button Wheel Up" "Button Wheel Down" "Button Horiz Wheel Left" "Button Horiz Wheel Right"
		Button state:
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 0:
		 Label: Rel X
		 Range: -1.000000 - -1.000000
		 Resolution: 0 units/m
		 Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 1:
		 Label: Rel Y
		 Range: -1.000000 - -1.000000
		 Resolution: 0 units/m
		 Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 2:
		 Label: Rel Horiz Scroll
		 Range: -1.000000 - -1.000000
		 Resolution: 0 units/m
		 Mode: relative
		Class originated from: 10. Type: XIValuatorClass
		Detail for Valuator 3:
		 Label: Rel Vert Scroll
		 Range: -1.000000 - -1.000000
		 Resolution: 0 units/m
		 Mode: relative
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 2
		 type: 2 (horizontal)
		 increment: 15.000000
		 flags: 0x0
		Class originated from: 10. Type: XIScrollClass
		Scroll info for Valuator 3
		 type: 1 (vertical)
		 increment: 15.000000
		 flags: 0x0
```
Makes sense that the way keyboards are represented has changed. In case you are interested in working on it (ofc no pressure), let me know how can I help. I am happy to test and/or povide you any further info you'd need.

**Comment by VP1147** [comment] 2020-11-22 14:38
Yes, can be a good help for me to make it work on more devices.
Please send the output of `xinput list-props "Lenovo TrackPoint Keyboard II Mouse"`
Mine is:
```
Device 'TPPS/2 IBM TrackPoint':
	Device Enabled (148):	1
	Coordinate Transformation Matrix (150):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Natural Scrolling Enabled (313):	0
	libinput Natural Scrolling Enabled Default (314):	0
	libinput Scroll Methods Available (317):	0, 0, 1
	libinput Scroll Method Enabled (318):	0, 0, 1
	libinput Scroll Method Enabled Default (319):	0, 0, 1
	libinput Button Scrolling Button (326):	2
	libinput Button Scrolling Button Default (327):	2
	libinput Middle Emulation Enabled (328):	0
	libinput Middle Emulation Enabled Default (329):	0
	libinput Accel Speed (320):	0.000000
	libinput Accel Speed Default (321):	0.000000
	libinput Accel Profiles Available (330):	1, 1
	libinput Accel Profile Enabled (331):	1, 0
	libinput Accel Profile Enabled Default (332):	1, 0
	libinput Left Handed Enabled (322):	0
	libinput Left Handed Enabled Default (323):	0
	libinput Send Events Modes Available (290):	1, 0
	libinput Send Events Mode Enabled (291):	0, 0
	libinput Send Events Mode Enabled Default (292):	0, 0
	Device Node (293):	"/dev/input/event2"
	Device Product ID (294):	2, 10
	libinput Drag Lock Buttons (324):	<no items>
	libinput Horizontal Scroll Enabled (325):	1
```

**Comment by mateuszwieloch** [comment] 2020-11-22 17:57
```
$ xinput list-props 10
Device 'Lenovo TrackPoint Keyboard II Mouse':
	Device Enabled (179):	1
	Coordinate Transformation Matrix (181):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Natural Scrolling Enabled (314):	0
	libinput Natural Scrolling Enabled Default (315):	0
	libinput Scroll Methods Available (316):	0, 0, 1
	libinput Scroll Method Enabled (317):	0, 0, 0
	libinput Scroll Method Enabled Default (318):	0, 0, 0
	libinput Button Scrolling Button (319):	2
	libinput Button Scrolling Button Default (320):	2
	libinput Button Scrolling Button Lock Enabled (321):	0
	libinput Button Scrolling Button Lock Enabled Default (322):	0
	libinput Middle Emulation Enabled (323):	0
	libinput Middle Emulation Enabled Default (324):	0
	libinput Accel Speed (325):	0.264706
	libinput Accel Speed Default (326):	0.000000
	libinput Accel Profiles Available (327):	1, 1
	libinput Accel Profile Enabled (328):	1, 0
	libinput Accel Profile Enabled Default (329):	1, 0
	libinput Left Handed Enabled (330):	0
	libinput Left Handed Enabled Default (331):	0
	libinput Send Events Modes Available (299):	1, 0
	libinput Send Events Mode Enabled (300):	0, 0
	libinput Send Events Mode Enabled Default (301):	0, 0
	Device Node (302):	"/dev/input/event9"
	Device Product ID (303):	6127, 24814
	libinput Drag Lock Buttons (332):	<no items>
	libinput Horizontal Scroll Enabled (333):	1
```

**Comment by VP1147** [comment] 2020-11-22 19:01
Ok. It seens that I can call `xinput set-prop <device-id> "libinput Accel Speed" <value>` to change the acceleration instead of relying on the sysfs. Next step is to implement a way to find out the correct device ID, also a way to change the speed (this option only affects the acceleration).

**Comment by VP1147** [comment] 2020-11-22 19:18
Also send the output of `xinput list | grep "TrackPoint" | cut -d '=' -f 2 | cut -f 1`.

**Comment by mateuszwieloch** [comment] 2020-11-22 20:00
Grepping and cutting correctly extracts IDs:
```
$ xinput list | grep "TrackPoint"
⎜   ↳ Lenovo TrackPoint Keyboard II Mouse     	id=10	[slave  pointer  (2)]
⎜   ↳ Lenovo TrackPoint Keyboard II Consumer Control	id=11	[slave  pointer  (2)]
⎜   ↳ TPPS/2 Elan TrackPoint                  	id=19	[slave  pointer  (2)]
    ↳ Lenovo TrackPoint Keyboard II           	id=9	[slave  keyboard (3)]
    ↳ Lenovo TrackPoint Keyboard II System Control	id=12	[slave  keyboard (3)]
    ↳ Lenovo TrackPoint Keyboard II Consumer Control	id=21	[slave  keyboard (3)]
```

```
$ xinput list | grep "TrackPoint" | cut -d '=' -f 2 | cut -f 1
10
11
19
9
12
21
```

**Comment by VP1147** [comment] 2020-11-23 14:20
Yeah. It worked. But notice how many IDs it returned. This can be solved by grepping the world `"pointer"`, so
`$ xinput list | grep "TrackPoint" | grep "pointer" | cut -d '=' -f 2 | cut -f 1` would return
```
⎜   ↳ Lenovo TrackPoint Keyboard II Mouse     	id=10	[slave  pointer  (2)]
⎜   ↳ Lenovo TrackPoint Keyboard II Consumer Control	id=11	[slave  pointer  (2)]
⎜   ↳ TPPS/2 Elan TrackPoint                  	id=19	[slave  pointer  (2)]
```
These option can be presented to the user to choice. So, you could choice between external keyboard (id=10) and built-in keyboard (id=19), and I have no idea of what this "Consumer Control" is, actually. Can be a real help if you send the output of `xinput list 11`.

**Comment by mateuszwieloch** [comment] 2020-11-26 20:46
```
Lenovo TrackPoint Keyboard II Consumer Control	id=20	[slave  keyboard (3)]
	Reporting 1 classes:
		Class originated from: 20. Type: XIKeyClass
		Keycodes supported: 248
```
Keycode 248 seems to be "ExSel (Extend Selection) key of IBM 3270 keyboard layout." [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode). So it's basically one of the additonal proprietary keys on the keyboard (I'm not even sure which one).

It seems safe to ignore it.

**Comment by VP1147** [comment] 2020-12-05 19:01
Need to figure out a way to set the acceleration. Also I don't think `xinput set-prop <device-id> "libinput Accel Speed" <value>` is working on my laptop. Could you changing your trackpoint speed with this command?

**Comment by mateuszwieloch** [comment] 2020-12-06 06:55
Acceleration speed seems to be working for me. Setting it to 0 on my laptop's TrackPoint (which seems to be the minimum accepted value) makes it much less jumpy than 1 (maximum).
```
xinput set-prop 14 "libinput Accel Speed" 0
```
I wish there was also pure speed exposed, not just acceleration, but I don't see anything like that among props, so it's probably not exposed by libinput.

**Comment by VP1147** [comment] 2020-12-07 14:35
Yeah, I'm still searching for a way of setting up speed on newer Thinkpads, as it's the main purpose of this code.
I'm testing the xinput method on [this branch](https://github.com/VP1147/thinker/tree/xinput), could you try to execute thinker.sh and send the output?

**Comment by mateuszwieloch** [comment] 2020-12-24 00:55
Sorry for slow turnaround this time.

```
$ ./thinker.sh
Select the device to use: 
TPPS/2 Elan TrackPoint (14)
Traceback (most recent call last):
  File "thinker.py", line 38, in <module>
    s1, s2 = fetch()
  File "thinker.py", line 10, in fetch
    with open(sys.argv[2], "r") as speed:
IndexError: list index out of range
```

**Comment by VP1147** [comment] 2020-12-25 19:52
Hi. No problems my friend.
`TPPS/2 Elan TrackPoint (14)`
It means that the new detection method is working good. 
Still I can't find a way to change sensitivity/acceleration via _xinput_.
Anyway, I'll finish the implementation and merge to master.

**Comment by VP1147** [comment] 2020-12-25 20:38
Done. Can you test it again before I commit to master?
I removed the _Speed_ bar, now It have only a _Acceleration_ bar. It is working good on my T410,
now I need to know if it's working on your newer model.

**Comment by mateuszwieloch** [comment] 2020-12-25 21:28
It is indeed working great! Good job.

Also: Merry Christmas! 🎄

**Comment by VP1147** [comment] 2020-12-27 15:39
Merged.

**Closed as completed** 2021-01-27 16:09 UTC
